server:
  port: 1111 #端口
  servlet:
    context-path: /client #工程名
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server1:8762/eureka/ #eureka注册端地址
  instance:
    instance-id: project-client #eureka展示实例名称
spring:
  application:
    name: project-client #eureka注册名称
